stages:
  data_ingestion:
    cmd: python src/deepClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/deepClassifier/pipeline/stage_01_data_ingestion.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/PetImages
  preapre_base_model:
    cmd: python src/deepClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/deepClassifier/pipeline/stage_02_prepare_base_model.py
      - configs/config.yaml
    outs:
      - artifacts/prepare_base_model/base_model_updated.h5
      - artifacts/prepare_base_model/base_model.h5
  training:
    cmd: python src/deepClassifier/pipeline/stage_03_training.py
    deps:
      - src/deepClassifier/pipeline/stage_03_training.py
      - configs/config.yaml
    outs:
      - artifacts/prepare_callbacks/tensorboard_log_dir
      - artifacts/prepare_callbacks/checkpoint_dir/model.h5
      - artifacts/training/model.h5